-- ============================================================
--  Smart Attendance System — Database Schema
--  Compatible: MySQL 8.0+ / PostgreSQL 14+ / SQLite 3.35+
-- ============================================================

-- ─── TEACHERS ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS teachers (
    id              VARCHAR(50)  PRIMARY KEY,
    name            VARCHAR(100) NOT NULL,
    email           VARCHAR(150) UNIQUE,          -- optional, not required on register
    department      VARCHAR(100),
    password_hash   VARCHAR(200) NOT NULL,         -- PBKDF2-SHA256 hash
    role            VARCHAR(20)  NOT NULL DEFAULT 'teacher',
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ─── SESSIONS ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS sessions (
    id          INTEGER      PRIMARY KEY AUTOINCREMENT,
    teacher_id  VARCHAR(50)  NOT NULL REFERENCES teachers(id),
    subject     VARCHAR(100) NOT NULL,
    otp         VARCHAR(6)   NOT NULL,
    lat         REAL         NOT NULL,
    lon         REAL         NOT NULL,
    radius      INTEGER      NOT NULL DEFAULT 100,
    created_at  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    expires_at  TIMESTAMP,
    is_active   BOOLEAN      DEFAULT 1
);

-- ─── ATTENDANCE ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS attendance (
    id           INTEGER     PRIMARY KEY AUTOINCREMENT,
    session_id   INTEGER     NOT NULL REFERENCES sessions(id),
    student_id   VARCHAR(50) NOT NULL,
    student_name VARCHAR(100) NOT NULL,
    device_id    VARCHAR(200) NOT NULL,
    lat          REAL        NOT NULL,
    lon          REAL        NOT NULL,
    distance     REAL        NOT NULL,
    is_flagged   BOOLEAN     DEFAULT 0,
    flag_reason  TEXT,
    marked_at    TIMESTAMP   DEFAULT CURRENT_TIMESTAMP
);

-- ─── DEVICE REGISTRY ──────────────────────────────────────
CREATE TABLE IF NOT EXISTS devices (
    id            INTEGER     PRIMARY KEY AUTOINCREMENT,
    session_id    INTEGER     NOT NULL REFERENCES sessions(id),
    device_id     VARCHAR(200) NOT NULL,
    student_id    VARCHAR(50) NOT NULL,
    registered_at TIMESTAMP   DEFAULT CURRENT_TIMESTAMP
);

-- ─── INDEXES ──────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_attendance_session ON attendance(session_id);
CREATE INDEX IF NOT EXISTS idx_attendance_student ON attendance(student_id);
CREATE INDEX IF NOT EXISTS idx_devices_session    ON devices(session_id);
CREATE INDEX IF NOT EXISTS idx_sessions_teacher   ON sessions(teacher_id);

-- ─── SEED DEFAULT TEACHERS (run once on fresh DB) ─────────
-- These replace the hardcoded _users dict from jwt_service.py.
-- Passwords are PBKDF2-SHA256 hashes — generated by jwt_service._hash_pw()
-- To regenerate: python3 -c "from app.auth.jwt_service import _hash_pw; print(_hash_pw('yourpassword'))"
--
-- INSERT OR IGNORE INTO teachers (id, name, password_hash, role)
-- VALUES ('teacher_001', 'Prof. Sharma', '<hash_here>', 'teacher');